### ISSUE TITLE
Como usuario puedo filtrar por otro tipo de Instituciones

### ISSUE THREAD

**Issue by rodowi** [mxabierto/ng-ckan#101]

**Comment by rodowi** [comment]
Como usuario puedo filtrar por
- Órganos desconcentrados
- descentralizados
- autónomos
- Poder Judicial

**Comment by chuckcfs** [comment]
¿es posible agregar un vocabulario a instituciones para determinar que nivel de gobierno es? cc @urkonn

**Comment by urkonn** [comment]
@chuckcfs el tag vocabulary es a nivel de dataset, déjame ver si es posible de otra forma

**Comment by carlosmaya** [comment]
ya están creados un par de issues en Adela para ayudar a resolver este punto

https://github.com/mxabierto/adela/issues/227

https://github.com/mxabierto/adela/issues/233

**Comment by carlosmaya** [comment]
se agregará al vocabulario de CKAN *Organismos Autónomos*

mxabierto/dgm-ansible/issues/54

**Comment by rodowi** [comment]
ya quedó no?

pero surgió #143
