### ISSUE TITLE
¿Cómo podemos agregar una referencia a la página de las organizaciones en datos.gob.mx?

### ISSUE THREAD

**Issue by rodowi** [mxabierto/ng-ckan#105]
- Definir cómo vamos agregar links de organizaciones
- Sería con el campo dcat:landingPage

http://www.w3.org/ns/dcat#landingPage
https://github.com/mxabierto/adela/issues/147

CONEVAL es el que más lo pide:
http://catalogo.datos.gob.mx/api/3/action/organization_show?id=coneval

**Comment by carlosmaya** [comment]
entonces dcat:landingPage  será el link al home de las organizaciones o al diccionario de datos?

**Comment by carlosmaya** [comment]
ya entendí, del inventario de datos vamos a usar el ds:dataDictionary  para que sea el dcat:landingPage

https://github.com/mxabierto/adela/issues/147

https://github.com/mxabierto/ckanops/issues/19

**Comment by rodowi** [comment]
LIgado al #60

**Comment by carlosmaya** [comment]
closed by mxabierto/ng-ckan#260
