### ISSUE TITLE
Agregar más metadatos por recursos

### ISSUE THREAD

**Issue by carlosmaya** [mxabierto/ng-ckan#108]
Al menos los que ya están en catalogo.datos.gob.mx -- comentado por @rodowi

**Comment by chuckcfs** [comment]
no este esta englobado en el #57 ?

**Comment by carlosmaya** [comment]
ok, si es así solo confirma para cerrarlo, mas bien fue porque no lo encontraba

**Comment by chuckcfs** [comment]
yo creo que sí no? ya de ese sólo faltaba la parte del diseño
