### ISSUE TITLE
Las URLs de mxabierto.github.io/ng-ckan deben estar bajo el dominio datos.gob.mx

### ISSUE THREAD

**Issue by rodowi** [mxabierto/ng-ckan#111]
[dgm](https://github.com/mxabierto/dgm) ya tiene el CNAME de datos.gob.mx https://github.com/mxabierto/dgm/blob/gh-pages/CNAME, pero [ng-ckan](https://github.com/mxabierto/ng-ckan) sólo vive en github.io. Dado que no podemos duplicar dos CNAME registries (o me equivoco?) tenemos que buscar un subdominio para el ng-ckan, como buscador.datos.gob.mx, no?

¿qué opinan?

**Comment by rodowi** [comment]
Este lo arregla con subdominios como lo sugerí:

Multiple GitHub Pages and custom domains via DNS
http://stackoverflow.com/questions/10685961/multiple-github-pages-and-custom-domains-via-dns

**Comment by bcessa** [comment]
IMO: si todo los tenemos bajo un mismo dominio simplifica tareas administrativas como habilitar HTTPS en todos los servicios utilizando un solo certificado wildcard: *.datos.gob.mx ;)

**Comment by rodowi** [comment]
got it, entonces usemos un subdominio para ng-ckan

como ya tenemos http://catalogo.datos.gob.mx/ (para el viejo catálogo), propongo busca.datos.gob.mx para ng-ckan

cc: @chuckcfs

**Comment by urkonn** [comment]
De acuerdo, todo es más fácil con subdominios :)

**Comment by chuckcfs** [comment]
si, me parece bien así con un subdominio, y el "busca" me late

**Comment by rodowi** [comment]
Listo, PR #113 lo resuelve

**Comment by carlosmaya** [comment]
awesome!!
