### ISSUE TITLE
Truncar descripciones largas de datasets, o agregar un view-more

### ISSUE THREAD

**Issue by rodowi** [mxabierto/ng-ckan#112]
p. ej. http://mxabierto.github.io/ng-ckan/#/instituciones/cenapred

**Comment by carlosmaya** [comment]
En la descripciones de la organización y  conjuntos

**Comment by chuckcfs** [comment]
@rodowi cc: @carlosmaya  esto en la nueva versión no es problema

<img width="1233" alt="screen shot 2015-10-19 at 17 07 02" src="https://cloud.githubusercontent.com/assets/1383865/10592783/f51b56c6-7683-11e5-89b0-985e77d47e99.png">

**Comment by rodowi** [comment]
:open_mouth: 

no hay descripciones de datasets en el nuevo diseño @carlosmaya @mxabierto/la-agencia ?!

**Comment by chuckcfs** [comment]
así es, sólo se muestra la descripción en la vista detalles, en las listas es el título

**Comment by diegobeauroyre** [comment]
¿lo metemos?

**Comment by chuckcfs** [comment]
salvo su mejor opinion, yo no lo creo necesario

**Comment by carlosmaya** [comment]
Está considerado en el nuevo diseño, propongo que se trunque a 20 palabras
