### ISSUE TITLE
No se muestran las imágenes de los logs en el detalle de cada grupo

### ISSUE THREAD

**Issue by carlosmaya** [mxabierto/ng-ckan#115]
Al momento de visualizar el detalle para cada Grupo ( ReconstrucciónMX, Segundo Informe y Tu Gobierno en Mapas ) la imagen del logo está rota

![ss_reconstruccionmx](https://cloud.githubusercontent.com/assets/2633527/8525058/4b4f4506-23c4-11e5-92b3-75b693178a4c.png)

![ss_segundo_informe](https://cloud.githubusercontent.com/assets/2633527/8525064/51a3a4f6-23c4-11e5-8010-d7eb1ac69b8c.png)

![ss_tu_gobierno_mapas](https://cloud.githubusercontent.com/assets/2633527/8525069/561270f8-23c4-11e5-9b6c-2e6ad7fb4df6.png)

**Comment by carlosmaya** [comment]
Los logos de `ReconstrucciónMX` y `Tu Gobierno en Mapas` no hacen referencia a ningún recurso

![logo_reconstruccionmx_02](https://cloud.githubusercontent.com/assets/2633527/8525607/8dc06502-23c7-11e5-9a42-f917cb79abea.png)

![logo_tu_gob_mapas_03](https://cloud.githubusercontent.com/assets/2633527/8525610/9188497a-23c7-11e5-8bb5-766444097bb5.png)

**Comment by rodowi** [comment]
El problema viene del API de CKAN:

Lo podemos resolver usando ADELA, github.com/mxabierto/assets, o ...

**Comment by haxdai** [comment]
Pasa lo mismo en el detalle de los datasets de las instituciones

<img width="1010" alt="captura de pantalla 2015-09-18 a las 18 34 50" src="https://cloud.githubusercontent.com/assets/7064389/9973165/fc01802c-5e33-11e5-9cd9-3215cb770698.png">

**Comment by rodowi** [comment]
como que le falta el base url @haxdai

hey @chuckcfs cómo generas las rutas de los logos en la vista de datasets?

**Comment by chuckcfs** [comment]
se supone que el JSON de la organización trae un campo `image_display_url` pero es el que nunca es consistente, en algunas no viene, en otros viene sólo un nombre de archivo y en otros un path, o al menos así estaba hace unos meses, es lo mismo que en instituciones

**Comment by haxdai** [comment]
Oigan @rodowi @chuckcfs, la cosa podría ser la línea 8 del archivo de vista [resources.html](https://github.com/mxabierto/ng-ckan/blob/master/app/views/resources.html)?

````
<img ng-src="{{dataset.organization.image_url}}" alt="Logo de {{dataset.organization.title}}" />
````

En otras vistas que usan la imagen de la organización se usa la propiedad ``image_display_url`` en vez de ``image_url``.

Incluso parece que la propiedad que viene del JSON es `ìmage_display_url``

<img width="726" alt="captura de pantalla 2015-09-21 a las 13 27 39" src="https://cloud.githubusercontent.com/assets/7064389/10000899/8ffb7008-6064-11e5-9ba3-63bc64aaf319.png">

No tengo chance de probarlo, pero igual y podría ser por ahí.

**Comment by chuckcfs** [comment]
que tal @haxdai eso que mencionas son cosas distintas, la vista `resource.html` es para datasets en el JSON del dataset la imagen viene en el campo `organization.image_name`

<img width="539" alt="screen shot 2015-09-21 at 13 32 23" src="https://cloud.githubusercontent.com/assets/1383865/10001003/3b34ef94-6065-11e5-8c83-f13116ad80aa.png">

pero es el mismo asunto, no vienen estandarizadas, en algunos datasets es una URL completa y en otros (como en el del screen) sólo es el nombre del archivo, sin ningun path.

En organizaciones la vista es `organization.html` y en ese JSON el campo de la imagen viene en `image_display_url` pero lo mismo, no viene bien ese campo, y eso es desde ckan, si ves por ejemplo en esta no viene el campo:

http://busca.datos.gob.mx/#/grupos/tu-gobierno-en-mapas

pero en esta sí

http://busca.datos.gob.mx/#/grupos/tercer-informe-de-gobierno

y en ambos se esta usando el mismo `image_display_url`, es problema de los datos, no del buscador :scream:

**Comment by haxdai** [comment]
Entiendo @chuckcfs. El caso de tu gobierno en mapas y de reconstrucciónMX (le llamaré caso 1) puede deberse a que en CKAN esos grupos no tienen dada de alta una imagen?

<img width="1006" alt="captura de pantalla 2015-09-21 a las 13 43 38" src="https://cloud.githubusercontent.com/assets/7064389/10001384/140e81a8-6067-11e5-94eb-c7ea28e2eca1.png">

Seguramente en la aplicación CKAN desde catalogo.datos.gob.mx se agrega a conveniencia el placeholder de la imagen para que no aparezca una imagen rota.

En el caso de ng-ckan, podría usarse un placeholder en esos casos, si es que no se está usando. El API sólo regresa el campo vacío.

**Comment by chuckcfs** [comment]
claro que si @haxdai, pues esa es la cosa, a mí ania o enrique no recuerdo quien en hace unas semanas me pidieron que pusiera un placeholder a todas, y cuando salio el segundo informe me dijeron que pusiera la imagen de la organización y no se quien se iba a encargar de subirlas, si quieren se pueden poner así como dices, un placeholder si no hay imagen, si gustas definanlo ustedes como prefieren que sea, y ahora que estoy trabajando en la segunda versión (para este viernes) lo implementamos.

Sólo si me gustaría que ya como se decida si esten todos quienes toman esas desiciones de acuerdo para no tener que estar cambiando lo mismo una y otra vez como ha sido hasta ahora.

**Comment by haxdai** [comment]
@chuckcfs Creo que lo tendrías que revisar con presidencia, yo soy un contribuidor externo, un simple coder buscando apoyar en el código y en identificar y/o solucionar bugs. No me mueve en este momento más que el interés personal en el tema de datos abiertos y las aplicaciones que se desarrollan.

+1 por que se pongan de acuerdo y se defina el requerimiento de manera apropiada.

**Comment by chuckcfs** [comment]
ah perfecto, lo siento, pense que estabas dentro del equipo de presidencia, de antemano muchas gracias por el apoyo :smile:

**Comment by haxdai** [comment]
No problemo

**Comment by haxdai** [comment]
Creo que la mejor opción al momento es la que propone @rodowi de usar los assets de ADELA, ya que las rutas para los assets en CKAN no son consistentes.

**Comment by carlosmaya** [comment]
de hecho ya hay imágenes unas 40 imágenes de logos ahí

https://github.com/mxabierto/assets/tree/master/img/logos-instituciones

@chuckcfs me parece que solo restaría validar que los nombres sean los del `slug`

**Comment by chuckcfs** [comment]
@carlosmaya exacto, eso fue lo que acordamos este viernes no? de ese repo las vamos a tomar usando el slug de adela.

creo que lo mejor sería poner o bien en un folder `logos` y llamar la imagen con el slug, o la otra, usar un folder con el slug y que todas sean `logo.png` esto por si más adelante va a haber más imagenes relacionadas a las organizaciones

**Comment by carlosmaya** [comment]
@chuckcfs los logos sin aparecer, ¿estos también los está intentando jalar de `assets`? si es así, ¿cómo debemos de subirlos para que los tome?

**Comment by carlosmaya** [comment]
closed by #137
