### ISSUE TITLE
No hay conjunto de datos dentro del Grupo de Segundo Informe de Gobierno

### ISSUE THREAD

**Issue by carlosmaya** [mxabierto/ng-ckan#116]
Al momento de ver el detalle del Grupo Segundo Informe de Gobierno no se muestra ningún conjunto de datos

![ss_segundo_informe](https://cloud.githubusercontent.com/assets/2633527/8525147/baca3fbc-23c4-11e5-8ffa-1f74bf22526e.png)

**Comment by carlosmaya** [comment]
Se elimino el grupo, ya que inicialmente se había creado para ligar los datos que no tenían Institución.

Los que correspondían al *Segundo Informe de Gobierno 2012-2013* ahora están bajo Presidencia

http://busca.datos.gob.mx/#/instituciones/presidencia

Ya no se muestra el grupo

![ckan_groups](https://cloud.githubusercontent.com/assets/2633527/8533021/b4cb96be-23f7-11e5-9cae-1e451cadb7c5.png)

**Comment by rodowi** [comment]
Lo validaste con Ania o Enrique @carlosmaya ?

**Comment by carlosmaya** [comment]
Valide con Enrique que los datos se movieron a Presidencia como institución y ya no estaban asociados al grupo. 

Después, en el channel de #dgm se le notifico a Ania de la eliminación del grupo y que los datos estaban ahora en Presidencia.

**Comment by rodowi** [comment]
:+1:
