### ISSUE TITLE
Poner un spinner o mensaje de "cargando" 

### ISSUE THREAD

**Issue by carlosmaya** [mxabierto/ng-ckan#117]
Checar issue relacionado en DGM  https://github.com/mxabierto/dgm/issues/136

- [ ] Pantalla inicial cuando se carga un grupo o institución
![ss_tu_gob_mapas_01](https://cloud.githubusercontent.com/assets/2633527/8525281/ab5e6084-23c5-11e5-9e7b-48ae5a363b76.png)

- [ ] Momento en que aparecen los conjuntos de datos
![ss_tu_gob_mapas_02](https://cloud.githubusercontent.com/assets/2633527/8525289/aff36536-23c5-11e5-836f-c4841dddde6e.png)

- [ ] Cuando se muestra el listado de instituciones

**Comment by diegobeauroyre** [comment]
Alguna vez propuse este: http://codepen.io/diegobeauroyre/pen/GgNBPe

**Comment by carlosmaya** [comment]
@chuckcfs acá esta lo del spinner
