### ISSUE TITLE
Como usuario puedo filtrar los datos por formato

### ISSUE THREAD

**Issue by carlosmaya** [mxabierto/ng-ckan#120]
P. ej.  `csv` ,`json` , etc

**Comment by rodowi** [comment]
![busqueda](https://cloud.githubusercontent.com/assets/705860/10526538/239d7ffa-7351-11e5-962a-b5ed897ff4d6.png)

1. Al presionar uno de los links en el círculo rojo
2. Se realiza un request a un endpoint que regresa un array de datasets (siguiendo el formato de otros endpoints de datos.gob.mx)
3. Los datasets deben ser aquellos que tengan recursos en un formato en particular

**Comment by rodowi** [comment]
Retos:

1. El tipo de formato está a nivel recurso, no dataset
2. No todos los recursos tienen registrado su metadato `format`
3. Algunos recursos están dentro de un ZIP

```json
{
    "distribution": [
        {
            "title": "CatálogoNacional",
            "description": "Centrosescolaresanivelnacional",
            "license": "http: //datos.gob.mx/libreusomx/",
            "downloadURL": "http: //fs.planeacion.sep.gob.mx/cct/cct.zip",
            "mediaType": "application/zip",
            "format": null,
            "byteSize": "9142021",
            "temporal": "Agosto2012-Julio2013",
            "spatial": "nacional"
        }
    ]
}
```

**Comment by rodowi** [comment]
### Ideas

1. Cronjob   
  a. Corre sobre http://catalogo.datos.gob.mx/api/3/action/package_search?q=  
  b. Revisa results[0].resources  
  c. Registra la cuenta de { id_dataset, format } en un storage  
  d. En un endpoint regresa los datasets que corresponden a un formato, e. g. GET /datasets?format=CSV  
2. Usar directamente el API de CKAN: probar catalogo.datos.gob.mx/dataset?res_format=CSV

**Comment by rodowi** [comment]
Got it
http://catalogo.datos.gob.mx/api/3/action/package_search?fq=res_format:CSV

**Comment by carlosmaya** [comment]
y para saber cuales son los tipos de archivos que hay en CKAN usamos de fractal

http://fractal-api.fractal.ai/?expr=(frequencies%20(map%20:format%20(db-find%20%22recursos%22)))

**Comment by rodowi** [comment]
o del endpoint de CKAN
http://demo.ckan.org/api/action/package_search?facet.field=[%22res_format%22]&rows=0

**Comment by rodowi** [comment]
El reto que queda es hacer un barrido por los resources y actualizarles el res_format viendo la extensión.

Esto ya lo hacía ckanops, pero no sé dónde quedó @urkonn.

@carlosmaya fractal revisa extensiones?

**Comment by rodowi** [comment]
podemos hacer un cronjob de esto:
https://github.com/mxabierto/ckanops/blob/88c12226285fc697d66f6f81eb0f6ef20d37d35d/ckanops/resource.py#L24

**Comment by carlosmaya** [comment]
@rodowi  hasta donde se, fractal está barriendo los recursos de CKAN y sacando las extensiones

**Comment by rodowi** [comment]
1. No administramos ese código, dominio, infraestructura; ¿para qué agregar dependencia externa?
2. Barren pero no actualizan. Necesitamos actualizar la metadata en CKAN.

Propongo: https://github.com/mxabierto/shogun/issues/12

**Comment by carlosmaya** [comment]
@rodowi entiendo lo de mxabierto/shogun#12 en ese mismo barrido también deberíamos guardar los tipos de formato que hay y cuantos tiene cada cosa

o ¿estamos pensando que la lista de formatos es fija? para mi tendría que ser dinámica y debe reflejar lo que tiene CKAN

**Comment by rodowi** [comment]
Por lo pronto usemos los que sabemos son más comunes ¿no crees?

**Comment by carlosmaya** [comment]
De acuerdo a los que tienen los de fractal este sería el top 5 a considerar y solamente poner el tipo de formato (sin la cantidad de recursos)

"shp": 1548
"KML": 972
"CSV": 851
"xlsx": 815,
"ZIP": 441
