### ISSUE TITLE
Cambiar el formato de las fechas a español

### ISSUE THREAD

**Issue by carlosmaya** [mxabierto/ng-ckan#121]

**Comment by carlosmaya** [comment]
![fechas-en-ingles](https://cloud.githubusercontent.com/assets/2633527/9147123/7e402a66-3d28-11e5-9548-2d797790e7b4.png)

**Comment by chuckcfs** [comment]
@carlosmaya @rodowi esto quedo resuelto hace ya algún tiempo

<img width="1105" alt="screen shot 2015-10-03 at 20 12 47" src="https://cloud.githubusercontent.com/assets/1383865/10265959/3638f1fc-6a0b-11e5-9163-4dd7782a575e.png">

**Comment by carlosmaya** [comment]
es correcto, pero en el rediseño otra vez se muestran en inglés en algunos
casos

**Comment by chuckcfs** [comment]
ah si, tienes la razon, ahorita lo corrijo
