### ISSUE TITLE
En algunas páginas no hay mensaje de "Cargando..."

### ISSUE THREAD

**Issue by rodowi** [mxabierto/ng-ckan#122]
Aprovecho que tengo conexión lenta para darme cuenta que algunas vistas no tienen mensaje de "Cargando...":

- [ ] Una institución: http://busca.datos.gob.mx/#/instituciones/ayuntamiento-de-san-pedro-garza-garcia
- [ ] Un dataset: http://busca.datos.gob.mx/#/conjuntos/indicadores-municipales-de-san-pedro-garza-garcia

**Comment by nez** [comment]
No se si les lata pero esta barra es muy fácil de poner de forma global http://chieffancypants.github.io/angular-loading-bar/

**Comment by rodowi** [comment]
Creo que necesitamos algo más explícito abajo del buscador. Es decir, dejar el mensaje donde se supone que se verán los resultados.
