### ISSUE TITLE
No hay filtro por ciudades

### ISSUE THREAD

**Issue by rodowi** [mxabierto/ng-ckan#143]
<img width="176" alt="screen shot 2015-09-28 at 10 54 59 am" src="https://cloud.githubusercontent.com/assets/705860/10140911/6d22fc8e-65cf-11e5-8515-88576c9fe37e.png">

**Comment by carlosmaya** [comment]
Se resolvió con v2.0[redesign]
![screen shot 2015-11-04 at 9 35 20 am](https://cloud.githubusercontent.com/assets/2633527/10942870/8294408a-82d7-11e5-9049-27f06432811e.png)
