### ISSUE TITLE
No jalan links a filtros por gov type

### ISSUE THREAD

**Issue by rodowi** [mxabierto/ng-ckan#144]
<img width="170" alt="screen shot 2015-09-28 at 11 25 46 am" src="https://cloud.githubusercontent.com/assets/705860/10141725/c254ecd6-65d3-11e5-87d1-a6d851d9c446.png">

**Comment by rodowi** [comment]
llevan a "#"

**Comment by rodowi** [comment]
en redesign desapareció esta lógica de búsqueda: https://github.com/mxabierto/ng-ckan/blob/a6daee0c130037aa4f34c403c29e95f0cfb2cf52/app/scripts/directives/govtypesmenu.js

**Comment by rodowi** [comment]
deberían ir a http://catalogo.datos.gob.mx/api/3/action/package_search?q=+vocab_gov_types:Estatal&rows=0

**Comment by carlosmaya** [comment]
la consulta por `gob=autonomos` no está regresando resultados en `redesign`

* Resultados busca.datos.gob.mx  actual

![screen shot 2015-09-30 at 9 15 34 am](https://cloud.githubusercontent.com/assets/2633527/10195588/00d43774-6754-11e5-93c1-888d5517cba8.png)

* Resultado redesign

![screen shot 2015-09-30 at 9 15 21 am](https://cloud.githubusercontent.com/assets/2633527/10195596/0abda6bc-6754-11e5-8abf-bd99037b9fee.png)

**Comment by chuckcfs** [comment]
@carlosmaya la consulta no regresa resultados porque no hay datos con el tag de `gov_types: Autonomos` pero eso es cosa de ckan o adela, no se cual

**Comment by rodowi** [comment]
El issue era que los links no funcionaban, i.e. apuntaban a #

**Comment by chuckcfs** [comment]
@rodowi ah ok, no pero eso ya quedo la semana pasada

**Comment by rodowi** [comment]
puedes referenciar el commit o PR que cierra esto @chuckcfs ?

**Comment by chuckcfs** [comment]
@rodowi done
