### ISSUE TITLE
No aparece el nombre de la dependencia al mostrar los resultados por gov_type

### ISSUE THREAD

**Issue by carlosmaya** [mxabierto/ng-ckan#152]
![screen shot 2015-09-30 at 8 59 16 am](https://cloud.githubusercontent.com/assets/2633527/10195152/d60618fc-6751-11e5-9d63-4a35f6eb752b.png)

**Comment by chuckcfs** [comment]
@carlosmaya esto viene desde ckan, por alguna razón los datasets tiene null en el campo `organization`

<img width="1406" alt="screen shot 2015-10-01 at 22 46 19" src="https://cloud.githubusercontent.com/assets/1383865/10239122/83a8d93a-688e-11e5-89a7-5b6c0e36f5fa.png">

**Comment by carlosmaya** [comment]
curl 'http://catalogo.datos.gob.mx/api/3/action/package_search?q=%2Bvocab_gov_types:(Federal)&rows=10&start=0' -H 'Host: catalogo.datos.gob.mx' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:41.0) Gecko/20100101 Firefox/41.0' -H 'Accept: application/json, text/plain, */*' -H 'Accept-Language: en-US,en;q=0.5' -H 'Accept-Encoding: gzip, deflate' -H 'Referer: http://ng-ckan.bitslice.net/' -H 'Origin: http://ng-ckan.bitslice.net' -H 'Connection: keep-alive'

**Comment by rodowi** [comment]
hay datasets que no tienen organización, como los de tu gobierno en mapas, o el de FONDEN. Lo que tienen son grupos

Podemos poner el nombre del grupo en ese espacio.
