### ISSUE TITLE
Ajustes a página de detalle de un Conjunto

### ISSUE THREAD

**Issue by carlosmaya** [mxabierto/ng-ckan#187]
- [ ] Incluir opciones para ordenar los datos de búsqueda
- [x] Agregar descripción a los recursos y truncar a 20 palabras.
- [x] Agregar la hora en las fechas de la Información Adicional
- [x] Corregir typo de "Correo de contact" 

![ng-ckan-187](https://cloud.githubusercontent.com/assets/2633527/10623301/9625c3c4-7753-11e5-84bc-82f714f20200.png)

**Comment by chuckcfs** [comment]
@carlosmaya en esta vista no se puede ordenar los resultados más que por título porque no es una búsqueda, es únicamente los `resources` del dataset

**Comment by carlosmaya** [comment]
**validated**
![screen shot 2015-10-23 at 9 51 40 am](https://cloud.githubusercontent.com/assets/2633527/10695885/b3d7909a-796b-11e5-9774-51df1dca4121.png)
