### ISSUE TITLE
Mostrar nombre del Grupo en la lista de conjuntos asociados

### ISSUE THREAD

**Issue by carlosmaya** [mxabierto/ng-ckan#241]
![agregar_nombre_grupo](https://cloud.githubusercontent.com/assets/2633527/12279018/22c2bd72-b94a-11e5-809d-2d9d94de5179.png)

**Comment by chuckcfs** [comment]
esto quedo resuelto desde el PR #196 

![screen shot 2016-02-18 at 18 24 17](https://cloud.githubusercontent.com/assets/1383865/13162786/dc7f2b30-d66c-11e5-9901-4a807c40f42d.png)
