### ISSUE TITLE
Mostrar nombre de la Institución en breadcrumb

### ISSUE THREAD

**Issue by carlosmaya** [mxabierto/ng-ckan#251]
![change_name](https://cloud.githubusercontent.com/assets/2633527/12338891/bfdfc7a6-bad7-11e5-9c74-cd0eabf70591.png)

**Comment by chuckcfs** [comment]
esto quedo resuelto desde el PR #196 

![screen shot 2016-02-18 at 18 21 53](https://cloud.githubusercontent.com/assets/1383865/13162769/b70c955e-d66c-11e5-91b4-d8586fe81c62.png)
