### ISSUE TITLE
Features to add new data?

### ISSUE THREAD

**Issue by Analect** [mxabierto/ng-ckan#259]
Sorry, I don't have any Spanish!
I found your angular implementation for CKAN on Github by chance. It looks great.
It seems most of the functionality is read-only, as defined in CkanService.js.
Are there plans to expose other aspects of the API using one of the CKAN node modules ... which would give an ability to add / edit data?
Thanks for your time and efforts.

**Comment by urkonn** [comment]
Hi @Analect , sorry for not responding earlier

This project uses a CKAN instance behind and consumes the API to get the data, that's why is read-only, we're using it as a front-end

**Comment by Analect** [comment]
@urkonn 
Thanks. I figured that was the case .. but wasn't sure if you were planning to expose a write capability on the front-end.
