### ISSUE TITLE
Generar búsqueda a partir de una petición GET

### ISSUE THREAD

**Issue by rodowi** [mxabierto/ng-ckan#37]
DGM pedirá datasets:

![screen shot 2015-02-20 at 3 38 29 am](https://cloud.githubusercontent.com/assets/705860/6284062/0410f6e4-b8b2-11e4-86f4-cbdf52bfa38b.png)

**Comment by rodowi** [comment]
- [ ] el search box actual debe hacer peticiones a CKAN
- [ ] agregar el search box en donde haya datasets, p. ej. datasets.html, organization.html, group.html
- [ ] tener un servicio por GET que pueda ser aprovechado por DGM

**Comment by chuckcfs** [comment]
Este issue es parte del buscador, aunque aún falta el de organización y grupo, supongo es el mismo buscador únicamente que se especificaría de que grupo u organización hay que buscar los datasets no?

El servicio que trae los resultados es el ckanService de Angular, en el tercer bullet tienes "tener un servicio por GET", ¿quieres que haga algún componente reusable fuera de Angular y que el ckanService lo use? ¿o lo hago como hasta ahorita comunicando directamente con el API?

**Comment by rodowi** [comment]
Este issue es era de DGM, pero quedó eliminado este feature hace varios sprints.
