### ISSUE TITLE
Algunas imagenes de organizaciones no cargan

### ISSUE THREAD

**Issue by rodowi** [mxabierto/ng-ckan#39]
Se debe a que en el image_url, vienen filenames. Probablemente son imgs cargadas en CKAN.

Caso de img con url completa
http://catalogo.datos.gob.mx/api/3/action/package_show?id=encuesta-nacional-de-satisfaccion-a-usuarios-del-servicio-de-guarderia-del-imss

Caso de img con url con nombre de archivo
http://catalogo.datos.gob.mx/api/3/action/package_show?id=estadistica-agropecuaria

*Sucede en organization_show, pero en organization_list viene completa la url*

```html
<img src="http://catalogo.datos.gob.mx/uploads/group/20150220-093135.570061logoone.png" alt="Logo de SAGARPA">
```

**Comment by chuckcfs** [comment]
@rodowi este issue parece que ya esta resuelto y se quedo abierto por alguna razón, existe un campo "image_display_url" en las organizaciones que en todas las existentes es el archivo de la imagen.

![screen shot 2015-05-29 at 4 25 21 pm](https://cloud.githubusercontent.com/assets/1383865/7893046/670b5af4-061f-11e5-8714-a990c8c85e4f.png)
![screen shot 2015-05-29 at 4 25 32 pm](https://cloud.githubusercontent.com/assets/1383865/7893047/670d5656-061f-11e5-9ab1-ca3ddfc8f9e9.png)
![screen shot 2015-05-29 at 4 25 37 pm](https://cloud.githubusercontent.com/assets/1383865/7893048/670dc186-061f-11e5-8e65-d9b5e09adabd.png)
