### ISSUE TITLE
Filtrar por tipo de gobierno

### ISSUE THREAD

**Issue by rodowi** [mxabierto/ng-ckan#46]
Federal, estatal, municipal

**Comment by rodowi** [comment]
El query está medio raro, es el endpoint de vocabulary_show

http://201.175.32.249/api/3/action/vocabulary_show?id=81b14fa7-a743-4031-8f92-80f7c18b25a2

http://docs.ckan.org/en/latest/api/index.html#ckan.logic.action.get.vocabulary_show

**Comment by chuckcfs** [comment]
Este issue queda cerrado con el PR #76
