### ISSUE TITLE
Falta la cuenta de contacto en los metadatos del dataset

### ISSUE THREAD

**Issue by rodowi** [mxabierto/ng-ckan#57]
¿a quién le puedo escribir si tengo dudas?

![screen shot 2015-02-26 at 11 49 51 am](https://cloud.githubusercontent.com/assets/705860/6397899/a854dee6-bdad-11e4-9492-5e9c84f5d40e.png)

**Comment by rodowi** [comment]
http://foro.datos.gob.mx/t/niveles-de-rios-conagua/68

**Comment by carlosmaya** [comment]
se resolvió con v2.0[redesign]

![screen shot 2015-11-03 at 6 43 59 pm](https://cloud.githubusercontent.com/assets/2633527/10926263/fa1345f2-825a-11e5-86d7-5d7373d542a4.png)
