### ISSUE TITLE
Actualizar mensaje de aviso de work-in-progress

### ISSUE THREAD

**Issue by rodowi** [mxabierto/ng-ckan#59]
nuevo aviso:

El catálogo de datos está en proceso de rediseño y publicación progresiva de nuevos conjuntos, para visitar la versión anterior ve a [catalogo.datos.gob.mx](http://catalogo.datos.gob.mx/dataset)

**Comment by simiographics** [comment]
@rodowi ya esta en master cc1d935eb91daa7a81ba4ea4b1f30251a979a1a3, pero hace falta meterlo a gh-pages, deberias de poner en el readme como se hace eso.

**Comment by rodowi** [comment]
:+1:

**Comment by rodowi** [comment]
ya lo agrego al README
