### ISSUE TITLE
Agregar link a landingPage de las Instituciones

### ISSUE THREAD

**Issue by rodowi** [mxabierto/ng-ckan#60]
Tiene que ser bastante visible, no se si en el panel izquierdo abajo del logo.

¿Qué opinan @diegobeauroyre @simiographics?

**Comment by simiographics** [comment]
No entiendo en donde es esto? Los links de arriba del catalogo? 'Conjuntos de datos', 'Instituciones', 'Grupos'

**Comment by carlosmaya** [comment]
relacionado con el #84 y #105
