### ISSUE TITLE
Agregar anchor links a los recursos

### ISSUE THREAD

**Issue by rodowi** [mxabierto/ng-ckan#64]
Esto sirve para que puedas dar un link directo a un recurso que esta en una lista larga como en 

http://mxabierto.github.io/ng-ckan/#/conjuntos/censo-de-escuelas-maestros-y-alumnos-de-educacion-basica-y-especial

**Comment by rodowi** [comment]
![screen shot 2015-04-03 at 12 51 17 pm](https://cloud.githubusercontent.com/assets/705860/6987016/4f120a4c-da00-11e4-9554-2ebe47599f0e.png)

**Comment by carlosmaya** [comment]
al parecer esto ya está cerrado
