### ISSUE TITLE
Algunos logos están rotos

### ISSUE THREAD

**Issue by chuckcfs** [mxabierto/ng-ckan#82]

**Comment by chuckcfs** [comment]
esto parece ser un issue con los records de los grupos y no con ng-ckan, en algunos records el campo "image_display_url" esta vacio y en otros no existe el archivo.

![screen shot 2015-05-29 at 4 27 41 pm](https://cloud.githubusercontent.com/assets/1383865/7893076/ab85ef82-061f-11e5-974d-8ac57e5b995a.png)

![screen shot 2015-05-29 at 4 22 42 pm](https://cloud.githubusercontent.com/assets/1383865/7893078/ad92eece-061f-11e5-941d-14e4ad755edd.png)

**Comment by rodowi** [comment]
http://mxabierto.github.io/ng-ckan/#/conjuntos/indicadores-mide-jalisco-sobre-campo

**Comment by chuckcfs** [comment]
esto es lo mismo, los datos que manda el api están incompletos, en la vista "instituciones" se usa el campo "image_display_url"

![screen shot 2015-06-10 at 4 53 28 pm](https://cloud.githubusercontent.com/assets/1383865/8095134/425bccc2-0f91-11e5-87cd-aa6f7653261a.png)

pero en la vista "conjunto" el api regresa sólo el nombre del archivo del logo de la organización, no la ruta completa, y en el campo "image_url", el campo "image_display_url"

![screen shot 2015-06-10 at 4 54 25 pm](https://cloud.githubusercontent.com/assets/1383865/8095158/8895a0d2-0f91-11e5-820d-f40b1f6c29c3.png)

Lo que se me ocurre si no se va a hacer cambios a ckan o a agregar el campo como el listar las organizaciones, es, al momento de desplegar un dataset, hacer una segunda llamada al api para sacar la información completa de la organización

**Comment by carlosmaya** [comment]
¿qué tan viable es que podamos guardar esas imágenes cuando aún están disponibles?

**Comment by carlosmaya** [comment]
Hay que hacer referencia a las imágenes en el Repo de Assets. Revisar PR

https://github.com/mxabierto/assets/pull/5

**Comment by rodowi** [comment]
relacionado con #115

**Comment by carlosmaya** [comment]
ya se muestran todos los logos de las Dependencias

![screen shot 2015-09-30 at 8 54 01 am](https://cloud.githubusercontent.com/assets/2633527/10194957/fd16e094-6750-11e5-8e87-8c5d212df812.png)

**Comment by carlosmaya** [comment]
los logos se deben agregar en el repo de 

http://github.com/mxabierto/assets
