### ISSUE TITLE
Agregar diccionario de datos en la vista de datasets

### ISSUE THREAD

**Issue by chuckcfs** [mxabierto/ng-ckan#84]

**Comment by rodowi** [comment]
Ligado al #105, ya que será landingPage el metadato

**Comment by rodowi** [comment]
Ejemplo
en ADELA se ven algunos landingPages
http://adela.datos.gob.mx/shcp/catalogo.json

Pero en CKAN no
http://catalogo.datos.gob.mx/api/3/action/package_show?id=presupuesto-de-egresos-de-la-federacion

cc: @urkonn

**Comment by rodowi** [comment]
Acá se captura el campo
https://github.com/mxabierto/ckanops/blob/88c12226285fc697d66f6f81eb0f6ef20d37d35d/ckanops/converters.py#L13

Pero seguro url por dataset no existe en CKAN, creo que se arregla agregandolo a los extras

**Comment by urkonn** [comment]
https://github.com/ckan/ckan/issues/1336

**Comment by carlosmaya** [comment]
closed by mxabierto/ng-ckan#260
