### ISSUE TITLE
Como usuario puedo ver el número de bases de datos que hay en datos.gob.mx

### ISSUE THREAD

**Issue by chuckcfs** [mxabierto/ng-ckan#85]

**Comment by chuckcfs** [comment]
he estado revisando la documentación del CKAN y aparentemente no hay un método para obtener esto, lo que habría que hacer es contar los resources de cada dataset, y me parece muy ineficiente, serías demasiadas llamadas al API

**Comment by carlosmaya** [comment]
ya se incluyen el número de recursos por Institución
