### ISSUE TITLE
Filtros nivel de gobierno en Instituciones

### ISSUE THREAD

**Issue by chuckcfs** [mxabierto/ng-ckan#89]
En el menu "Instituciones" en ng-ckan en este momento se muestra el filtro de niveles de gobierno igual que en la vista de datasets, sólo que no encuentro ningún método en el API para filtrar las instituciones por nivel de gobierno, hace sentido que se muestre ese menú? o es más conveniente quitarlo?

![screen shot 2015-05-25 at 3 47 25 pm](https://cloud.githubusercontent.com/assets/1383865/7802148/9d285970-02f5-11e5-81aa-24fedc274149.png)

**Comment by rodowi** [comment]
Se puede resolver con la convención de nombres: https://github.com/mxabierto/adela/wiki/Convenciones-de-nombre-de-organizaciones
