### ISSUE TITLE
Agregar instrucciones para testing

### ISSUE THREAD

**Issue by rodowi** [mxabierto/ng-ckan#91]
PhantomJS no responde cuando hacemos grunt test

Running "karma:unit" (karma) task
INFO [karma]: Karma v0.12.31 server started at http://localhost:8080/
INFO [launcher]: Starting browser PhantomJS
WARN [launcher]: PhantomJS have not captured in 60000 ms, killing.
INFO [launcher]: Trying to start PhantomJS again (1/2).
WARN [launcher]: PhantomJS have not captured in 60000 ms, killing.
INFO [launcher]: Trying to start PhantomJS again (2/2).

**Comment by rodowi** [comment]
```
diff --git a/package.json b/package.json
index e384e81..0d1f4cd 100644
--- a/package.json
+++ b/package.json
@@ -34,6 +34,7 @@
     "karma-jasmine-jquery": "^0.1.1",
     "karma-phantomjs-launcher": "^0.1.4",
     "load-grunt-tasks": "^1.0.0",
+    "phantomjs": "^1.9.17",
     "protractor": "^1.6.1",
     "time-grunt": "^1.0.0"
   },
```

tuve que agregar el módulo de phantomjs pero no solucionó el problema

por acá se sugiere downgrading
http://stackoverflow.com/questions/29219075/webdriver-unable-to-create-session-with-phantomjs

**Comment by chuckcfs** [comment]
@rodowi no se exactamente a que se deba, me paso hoy y estuve buscando y nada, reinicie mi maquina y corre sin problemas otra vez

![screen shot 2015-06-02 at 5 37 10 pm](https://cloud.githubusercontent.com/assets/1383865/7948896/0678a980-094e-11e5-8ac2-c8f6fec6bb6a.png)

las versiones de karma y phantomjs no son, porque no correría tampoco en el ambiente de build de Travis CI, es más bien algo del socket que abre PhantomJS, como que a veces dependiendo la carga de la maquina en donde corre se cierra

**Comment by carlosmaya** [comment]
no hay evidencia de que se haya presentado de nuevo
